---
title: "Untitled"
output: html_document
---

```{r}
rm(list=ls())
library(dplyr)
library(readr)
library(lubridate)
library(speedglm)
```


```{r}
X_train_fine <- read_csv('../precrime_data/X_train_fine.csv')
y_train_fine <- read_csv('../precrime_data/y_train_fine.csv')
X_test_fine <- read_csv('../precrime_data/X_test_fine.csv')
y_test_fine <- read_csv('../precrime_data/y_test_fine.csv')
```

```{r}
X_train_fine$DAY_HOUR = as.factor(paste(X_train_fine$COMPLAINT_DAYOFWEEK, X_train_fine$COMPLAINT_HOURGROUP, sep='_'))
X_train_fine$ADDR_PCT_CD = as.factor(X_train_fine$ADDR_PCT_CD)
X_train_fine$COMPLAINT_DATE <- ISOdate(X_train_fine$COMPLAINT_YEAR, X_train_fine$COMPLAINT_MONTH, X_train_fine$COMPLAINT_DAY)
X_train_fine$COMPLAINT_DECIMALDATE <- decimal_date(X_train_fine$COMPLAINT_DATE)
train_fine = merge(X_train_fine, y_train_fine, by="X1")
```

```{r}
X_test_fine$DAY_HOUR = as.factor(paste(X_test_fine$COMPLAINT_DAYOFWEEK, X_test_fine$COMPLAINT_HOURGROUP, sep='_'))
X_test_fine$ADDR_PCT_CD = as.factor(X_test_fine$ADDR_PCT_CD)
X_test_fine$COMPLAINT_DATE <- ISOdate(X_test_fine$COMPLAINT_YEAR, X_test_fine$COMPLAINT_MONTH, X_test_fine$COMPLAINT_DAY)
X_test_fine$COMPLAINT_DECIMALDATE <- decimal_date(X_test_fine$COMPLAINT_DATE)
test_fine = merge(X_test_fine, y_test_fine, by="X1")
```

```{r}
train_fine$YEARFRAC <- train_fine$COMPLAINT_DECIMALDATE %% 1
test_fine$YEARFRAC <- test_fine$COMPLAINT_DECIMALDATE %% 1
```

```{r}
y_pred_fine <- data.frame(X1=test_fine$X1)
```

```{r}
model <- speedglm(Homicide ~ ADDR_PCT_CD + DAY_HOUR + poly(COMPLAINT_DECIMALDATE, 3) + poly(YEARFRAC, 3) + poly(precipIntensity, 2) +poly(temperature, 2), family = poisson(link='log'), data=train_fine)
y_pred_fine$Homicide <- predict(model, newdata=test_fine, type='response')
print('.')

model <- speedglm(Rape ~ ADDR_PCT_CD + DAY_HOUR + poly(COMPLAINT_DECIMALDATE, 3) + poly(YEARFRAC, 3) + poly(precipIntensity, 2) +poly(temperature, 2), family = poisson(link='log'), data=train_fine)
y_pred_fine$Rape <- predict(model, newdata=test_fine, type='response')
print('.')

model <- speedglm(Robbery ~ ADDR_PCT_CD + DAY_HOUR + poly(COMPLAINT_DECIMALDATE, 3) + poly(YEARFRAC, 3) + poly(precipIntensity, 2) +poly(temperature, 2), family = poisson(link='log'), data=train_fine)
y_pred_fine$Robbery <- predict(model, newdata=test_fine, type='response')
print('.')

model <- speedglm(FelonyAssault ~ ADDR_PCT_CD + DAY_HOUR + poly(COMPLAINT_DECIMALDATE, 3) + poly(YEARFRAC, 3) + poly(precipIntensity, 2) +poly(temperature, 2), family = poisson(link='log'), data=train_fine)
y_pred_fine$FelonyAssault <- predict(model, newdata=test_fine, type='response')
print('.')

model <- speedglm(Burglary ~ ADDR_PCT_CD + DAY_HOUR + poly(COMPLAINT_DECIMALDATE, 3) + poly(YEARFRAC, 3) + poly(precipIntensity, 2) +poly(temperature, 2), family = poisson(link='log'), data=train_fine)
y_pred_fine$Burglary <- predict(model, newdata=test_fine, type='response')
print('.')

model <- speedglm(GrandLarceny ~ ADDR_PCT_CD + DAY_HOUR + poly(COMPLAINT_DECIMALDATE, 3) + poly(YEARFRAC, 3) + poly(precipIntensity, 2) +poly(temperature, 2), family = poisson(link='log'), data=train_fine)
y_pred_fine$GrandLarceny <- predict(model, newdata=test_fine, type='response')
print('.')

model <- speedglm(GrandLarcenyAuto ~ ADDR_PCT_CD + DAY_HOUR + poly(COMPLAINT_DECIMALDATE, 3) + poly(YEARFRAC, 3) + poly(precipIntensity, 2) +poly(temperature, 2), family = poisson(link='log'), data=train_fine)
y_pred_fine$GrandLarcenyAuto <- predict(model, newdata=test_fine, type='response')
print('.')

model <- speedglm(Fraud ~ ADDR_PCT_CD + DAY_HOUR + poly(COMPLAINT_DECIMALDATE, 3) + poly(YEARFRAC, 3) + poly(precipIntensity, 2) +poly(temperature, 2), family = poisson(link='log'), data=train_fine)
y_pred_fine$Fraud <- predict(model, newdata=test_fine, type='response')
print('.')

model <- speedglm(Forgery ~ ADDR_PCT_CD + DAY_HOUR + poly(COMPLAINT_DECIMALDATE, 3) + poly(YEARFRAC, 3) + poly(precipIntensity, 2) +poly(temperature, 2), family = poisson(link='log'), data=train_fine)
y_pred_fine$Forgery <- predict(model, newdata=test_fine, type='response')
print('.')

model <- speedglm(Arson ~ ADDR_PCT_CD + DAY_HOUR + poly(COMPLAINT_DECIMALDATE, 3) + poly(YEARFRAC, 3) + poly(precipIntensity, 2) +poly(temperature, 2), family = poisson(link='log'), data=train_fine)
y_pred_fine$Arson <- predict(model, newdata=test_fine, type='response')
print('.')

model <- speedglm(Drugs ~ ADDR_PCT_CD + DAY_HOUR + poly(COMPLAINT_DECIMALDATE, 3) + poly(YEARFRAC, 3) + poly(precipIntensity, 2) +poly(temperature, 2), family = poisson(link='log'), data=train_fine)
y_pred_fine$Drugs <- predict(model, newdata=test_fine, type='response')
print('.')

model <- speedglm(Weapons ~ ADDR_PCT_CD + DAY_HOUR + poly(COMPLAINT_DECIMALDATE, 3) + poly(YEARFRAC, 3) + poly(precipIntensity, 2) +poly(temperature, 2), family = poisson(link='log'), data=train_fine)
y_pred_fine$Weapons <- predict(model, newdata=test_fine, type='response')
print('.')

model <- speedglm(CriminalMischief ~ ADDR_PCT_CD + DAY_HOUR + poly(COMPLAINT_DECIMALDATE, 3) + poly(YEARFRAC, 3) + poly(precipIntensity, 2) +poly(temperature, 2), family = poisson(link='log'), data=train_fine)
y_pred_fine$CriminalMischief <- predict(model, newdata=test_fine, type='response')
print('.')

model <- speedglm(Other ~ ADDR_PCT_CD + DAY_HOUR + poly(COMPLAINT_DECIMALDATE, 3) + poly(YEARFRAC, 3) + poly(precipIntensity, 2) +poly(temperature, 2), family = poisson(link='log'), data=train_fine)
y_pred_fine$Other <- predict(model, newdata=test_fine, type='response')
print('.')
```

```{r}
(cor(y_test_fine$Rape, y_pred_fine$Rape))^2
```

```{r}
mean((y_test_fine$Rape - y_pred_fine$Rape)^2)
```

