"""Functions for working with American FactFinder files."""
import numpy as np
import pandas as pd

__PREFIXES = {
    'Bronx': '36005',
    'Brooklyn': '36047',
    'Staten Island': '36085',
    'Queens': '36081',
    'Manhattan': '36061'
}


def get_boro_prefixes():
    """Return the prefix dictionary."""
    return __PREFIXES


def get_full_census_tract_id(boro, tract_2010):
    """Convert (boro, tract) in NY Shapefile to census tract ID.

    Parameters
    ----------
    boro : string
        One of 'Brooklyn', 'Staten Island', etc.
    tract_2010 : string
        A six-character string representing the census tract ID.

    Returns
    -------
    FullCensusTractID : string
        The fully qualified ID for referring to a census tract
        in a file generated by American FactFinder
    """
    return '1400000US' + str(__PREFIXES[boro]) + str(tract_2010)


def read_census_info(path='../census_info/'):
    """Load the data from American FactFinder into a single dataframe."""
    inc = pd.read_csv(
        path + 'income/ACS_15_5YR_S1903_with_ann.csv',
        index_col='GEO.id', skiprows=[1]
    )
    inc_cols = pd.read_csv(
        path + 'income/ACS_15_5YR_S1903_metadata.csv',
        header=None, index_col=0, squeeze=True
    )
    age_sex = pd.read_csv(
        path + 'age_sex/ACS_15_5YR_S0101_with_ann.csv',
        index_col='GEO.id', skiprows=[1]
    )
    age_sex_cols = pd.read_csv(
        path + 'age_SEX/ACS_15_5YR_S0101_metadata.csv',
        header=None, index_col=0, squeeze=True
    )
    edu = pd.read_csv(
        path + 'edu/ACS_15_5YR_S1501_with_ann.csv',
        index_col='GEO.id', skiprows=[1]
    )
    edu_cols = pd.read_csv(
        path + 'edu/ACS_15_5YR_S1501_metadata.csv',
        header=None, index_col=0, squeeze=True
    )
    nyc_pop = age_sex[age_sex.index.map(lambda x: x[9:14]).isin(
        get_boro_prefixes().values()
    )]

    merged = pd.merge(
        pd.merge(
            # HC01_EST_VC01 = Total Population
            nyc_pop[['GEO.id2', 'GEO.display-label', 'HC01_EST_VC01']],
            inc[['HC02_EST_VC02']],     # Median Household Income
            left_index=True,
            right_index=True
        ),
        edu[['HC02_EST_VC18']],         # Percent of population with bachelors+
        left_index=True,
        right_index=True
    )

    data_columns = [
        'Population',
        'Median_Household_Income',
        'Percent_Bachelors_Degree'
    ]

    merged.columns = np.concatenate((merged.columns[:2], data_columns))

    for col in data_columns:
        merged[col] = pd.to_numeric(merged[col], errors='coerce')

    return merged
